services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"  # Keeps Ollama accessible to localhost
    volumes:
      - /mnt/dev/gguf_models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - ollama-network
    restart: unless-stopped

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:v0.5.12-cuda
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - WEBUI_AUTH=${WEBUI_AUTH}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - open-webui:/app/backend/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - ollama-network
    restart: always
    depends_on:
      - ollama

  llama-cpp:
    build:
      context: .
      dockerfile: ./Dockerfile.llama-cpp
    ports:
      - "8123:8000"
    volumes:
      - /mnt/models:/models/input
      - /mnt/dev/gguf_models:/models/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - ollama-network

networks:
  ollama-network:
    external: true

volumes:
  open-webui: